### ISSUE TITLE
Analytics Components

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#102]
### What is this for?

website

### Feature

As a server owner, I want to be able to easily see statistics about how my server is performing. I want to be able to visualize this data in different ways and compare  it against each other

### Ideal solution or implementation

Reusable analytics components that cover the following:

- [ ] Line Graph
- [ ] Bar Graph
- [ ] Table
- [ ] Stats display (title, amount, % change)

Some analytics that are displayed:

- [ ] Top question answers (Table, [avatar, username, # questions answered])
- [ ] Average response time to have questions solved (Stat display)
- [ ] Joins from Answer Overflow (Stat display, bar graph)
- [ ] Top search queries leading to your pages, (Table)
- [ ] View sources (Table, [bing, google, duckduckgo, etc)

Checklist before contributing:

- [ ] Light and Dark mode support for all components
- [ ] All components are accessible

Create this in the ui package, inside of the components folder in its own folder called './Analytics'

Create Storybook stories for each component to be able to quickly preview them

### Other context

Here are a few helpful references:

Legacy code for analytics on the old site (pretty ugly but might be helpful): https://github.com/RhysSullivan/AnalyticsComponents

Answer Overflow Server Dashboard:
![image](https://user-images.githubusercontent.com/39114868/215340022-394602e0-61c3-43ae-aae6-ad81fcda8791.png)

Discord Server Insights:
![image](https://user-images.githubusercontent.com/39114868/215340063-0a826347-68d3-41ae-9f26-ef68b49a02ea.png)

Tailwind UI Stats:
https://tailwindui.com/components/application-ui/data-display/stats

Recharts:
https://recharts.org/en-US/

**Comment by JolteonYellow** [comment]
I can do this :+1:

**Comment by RhysSullivan** [comment]
Also for consideration (no dark mode support) https://www.tremor.so/
