### ISSUE TITLE
1 Click Setup Developing

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#104]
### What is this for?

website

### Feature

As a developer, I want to be able to experiment with contributing to Answer Overflow quickly without having to go through a tedious setup process

### Ideal solution or implementation

Use either GitLab or GitHub codespaces with a hyperlink in the readme to provide a 1 click dev setup

**Comment by RhysSullivan** [comment]
https://www.gitpod.io/docs/introduction/getting-started#contribute-with-gitpod-badge reference

**Comment by RhysSullivan** [comment]
https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/setting-up-your-repository/adding-a-codespaces-badge

**Comment by JoltCode** [comment]
Sorta linked with #32

**Comment by RhysSullivan** [comment]
> Sorta linked with #32

I actually ended up deciding against #32 - I found as I was actually developing it was more annoying than helpful

**Comment by JoltCode** [comment]
Ahh okay yeah, I like the quietness of the ui package, haven't tried any others yet
