### ISSUE TITLE
Automate Storybook Accessibility Testing 

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#112]
### What is this for?

website

### Feature

As a developer, I want to 

### Ideal solution or implementation

Use these as a reference:
https://www.youtube.com/watch?v=rNLL0SICr9w
https://www.deque.com/axe/
https://storybook.js.org/blog/automate-accessibility-tests-with-storybook/

**Comment by JoltCode** [comment]
I'll do this! :+1:

**Comment by RhysSullivan** [comment]
Pass an env variable via a script specifying whether lightmode or darkmode

Run both at the same time in parallel

- [ ] Test light mode
- [ ] Test dark mode

**Comment by RhysSullivan** [comment]
https://stackoverflow.com/questions/25112510/how-to-set-environment-variables-from-within-package-json

**Comment by RhysSullivan** [comment]
"test-storybook-light": "THEME=light test-storybook --maxWorkers=2",
"test-storybook-dark": "THEME=dark test-storybook --maxWorkers=2",
