### ISSUE TITLE
Consider absolute paths with aliases

### ISSUE THREAD

**Issue by robotkutya** [AnswerOverflow/AnswerOverflow#12]
https://github.com/AnswerOverflow/AnswerOverflow/blob/9e304e353bac1aae7a4b889acbcd081c01fdbf81/packages/api/src/router/user_server_settings/user_server_settings.ts#L2

this can get out of hand quickly and make the code hard to read
```ts
# confusing
import foo from '../../../../../../hell.ts'
```

consider adding an ESLint rule to prevent these
https://eslint.org/docs/latest/rules/no-restricted-imports
```ts
...
'no-restricted-imports': [
      'error',
      {
        patterns: ['../..*'],
      },
    ],
...
```

after which we would get
```ts
# nice and readable
import foo from '@/path/to/hell.ts'
```

**Comment by RhysSullivan** [comment]
Added to #21 thanks for the suggestion!
