### ISSUE TITLE
Message reply functionality in message component

### ISSUE THREAD

**Issue by JoltCode** [AnswerOverflow/AnswerOverflow#130]
### What is this for?

website

### Feature

As a developer, I'd like the ability to create replies from messages to other messages, with the message component.

### Ideal solution or implementation

In the `Message` component, we should add the ability for messages to be replied between each other, mimicking the design of discord's reply feature.

### Alternative solutions or implementations

![image](https://user-images.githubusercontent.com/46378904/216402872-ac2d5ee4-7d15-4168-a80f-e73aea9c7bbd.png)

### Other context

The type def already exists, just the feature needs to be created.

**Comment by JoltCode** [comment]
I'll probably work on this today @RhysSullivan

**Comment by RhysSullivan** [comment]
Merged with #84
