### ISSUE TITLE
Design guidelines

### ISSUE THREAD

**Issue by JoltCode** [AnswerOverflow/AnswerOverflow#131]
### What is this for?

core

### Feature

As a developer, designer or a user, I would like a design guidelines file

### Ideal solution or implementation

This would contain:

- Brand Colours
- Colour Combinations
- Logos (and their respective colour variants)
- Fonts

And possibly:
- Accessibility guides (mention of what contrast ratios we require etc.)
- Spacing
- Components (only a few primitives

### Alternative solutions or implementations

This could be done through a markdown file, which could contain either the guidelines directly within it, or an image/pdf file within the markdown file itself.

Maybe we could also make and include a dedicated figma file? This could be included as well?

### Other context

N/A

**Comment by RhysSullivan** [comment]
https://trpc.io/media

https://discord.com/branding

Looking at branding guidelines may be a good reference
