### ISSUE TITLE
Speed Up Playwright Install

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#145]
### What is this for?

bot

### Feature

As a dev, I want my CI to run faster

### Ideal solution or implementation

https://github.com/microsoft/playwright/discussions/14292

https://playwright.bootcss.com/python/docs/next/ci

**Comment by JoltCode** [comment]
Related to #36?

**Comment by RhysSullivan** [comment]
Closed as duplicate of #36
