### ISSUE TITLE
Add To / Manage Server Card

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#147]
### What is this for?

bot

### Feature

As a server owner, I want an easy way to add the bot to my server 

### Ideal solution or implementation

A card with the following information:

[Server Icon]
[Server Name}
[Button](Manage Server/Add To Server)

**Comment by mwgiannini** [comment]
I can do this.

**Comment by RhysSullivan** [comment]
Couple references:

![image](https://user-images.githubusercontent.com/39114868/217691344-e1f5bb42-f713-4600-b804-66d91c2d7867.png)

![image](https://user-images.githubusercontent.com/39114868/217691361-de4b2307-592e-46a8-ad7a-e623ab51706a.png)

![image](https://user-images.githubusercontent.com/39114868/217691392-25759c05-fdf1-44e1-af73-98edf2e6af52.png)

**Comment by mwgiannini** [comment]
Great - thanks Rhys

**Comment by mwgiannini** [comment]
Update: Here is what I have so far

<img width="442" alt="Screenshot 2023-02-16 at 7 37 37 PM" src="https://user-images.githubusercontent.com/89871491/219521055-67531823-fe3b-46d4-a78a-5888384ede48.png">

**Comment by RhysSullivan** [comment]
Looks good! When you make a PR we'll be able to preview and get it merged

**Comment by RhysSullivan** [comment]
Closed in #147
