### ISSUE TITLE
Improve issue template, add pr template

### ISSUE THREAD

**Issue by JoltCode** [AnswerOverflow/AnswerOverflow#150]
All issue templates should be converted to .yml, and multiple other templates should be added.
A pull request template should be created as well

**Comment by RhysSullivan** [comment]
Types of issues we will be commonly creating:

- [ ] Dev Environment Improvement
- [ ] Documentation Improvement
- [ ] Website Page
- [ ] Discord Bot Feature
- [ ] Design
- [ ] Deployment
- [ ] Quick Idea (Repo owners only?)
- [ ] Other

**Comment by RhysSullivan** [comment]
Closed in #153 - Opening a new issue for PR templates
