### ISSUE TITLE
[Bot]: Dismiss Button

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#157]
### aspect

Menu, Mark Solution

### Suggestion?

I would like a dismiss button that is red and will dismiss the message that it is attached to. 

### Possible Solutions

It should be possible to add a dismiss button onto any message that is not ephemeral. i.e the mark solution instructions message. When this button is created, it should be a limited scope of who can use it. The people that can use it is anyone with the manage messages and higher permissions. Along with this, the user that this message is being sent in response to should be able to use this button

It is possible to custom ids on buttons, one approach for only letting the person the button responds to use it would be to do:
dismiss-[user_id] and then validate that in a custom parser

https://www.sapphirejs.dev/docs/Guide/application-commands/interaction-handlers/buttons

**Comment by JoltCode** [comment]
I can do this after #11

**Comment by JoltCode** [comment]
Need to focus on web stuff for now 👍

**Comment by RhysSullivan** [comment]
Closed in #331
