### ISSUE TITLE
[Dev Env]: Stop Using prettier ESlint Rule

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#158]
### aspect

Linting

### Suggestion?

Prettier recommends to not use the ESLint rule for formatting as it causes a lot of errors that are not actually errors, which distracts from the actual errors when developing. In order to solve this, prettier linting should be a separate step from ESLint 

### Possible Solutions

https://prettier.io/docs/en/integrating-with-linters.html

**Comment by JoltCode** [comment]
To confirm, would this result in the removal of prettier-eslint and making prettier completely separate from eslint?

**Comment by RhysSullivan** [comment]
Yeah I believe that's what they recommend - we'd still have prettier formatting it'd just be separate

**Comment by JoltCode** [comment]
Alright, sounds good. This would probably help us integrate how tailwind is encouraging we do linting/formatting in our code (with prettier)
