### ISSUE TITLE
[Needs Expansion]: Blog Site

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#164]
### Idea

We want a blog to be available at blog.answeroverflow.com. Contributors should be able to highlight their work on this blog and link to all of the things of theirs they want to promote when merging major features

**Comment by JoltCode** [comment]
We should start this by looking at a greater list of requirments, and then look from there on what technologies we could use.

Some ideas:
Astro
Sveltekit
Hugo

I do like the idea of using markdown, it would make it a lot easier to write and maintain.

**Comment by JoltCode** [comment]
https://nextra.site/

**Comment by RhysSullivan** [comment]
tracking at https://www.notion.so/answeroverflow/Blog-Site-c129c9c811e34a66ac057d291f3e4266?pvs=4
