### ISSUE TITLE
Website Hompage (/)

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#17]
### What is this for?

website

### Feature

As a user visiting Answer Overflow, I need a landing page that allows me to understand what features Answer Overflow offers and try it out

### Ideal solution or implementation

A homepage with the following elements:

Search Bar - Trial search
Example Search Button - Example for users who are new and don't know what query to use
Example Result Button - Highlights a good result (could be replaced with a random result button)
Communities on Answer Overflow - Demo real world use cases
Feature Overview

### Other context

Visit https://www.answeroverflow.com/ to see the existing landing page

**Comment by RhysSullivan** [comment]
Let's break down a bit more what we want out of this homepage 

The main value answer overflow has for server owners is that it indexes their help channel content into google - everything else is fluff

So, the very first thing we communicate is that you can index your help channel content into google

This is to initially spark interest and catch all of the potential people who are familiar with this problem and have been looking for a solution

We should maybe have a hero button here of "add to discord" to catch all the people who want to get started right away

Next up is we need to catch the people who are aware of this problem but don't understand why they should care about it 

To do this, we need to show them somehow the benefits of having their content indexed into google

Hit on some key points such as 
- Less repeat questions 
- More users joining the server
- More likely that your product will succeed

With that done and the user still scrolling, we then move onto the how this actually works in their server

This section shouldn't be too bogged down with details, instead it should hit on the major parts

- Works with any channel type
- Can be partially adopted 
- Only indexes content from users who want their content indexed

After that then we possibly also go into the other major features of answer overflow such as
- Analytics
- Help channel utils

**Comment by RhysSullivan** [comment]
https://m.youtube.com/watch?v=hWGgw1K-i8Y

**Comment by RhysSullivan** [comment]
https://heropatterns.com/

**Comment by JoltCode** [comment]
Maybe we could use gsap for some cool animations as well?

**Comment by RhysSullivan** [comment]
That could be cool - I think we don't want to get too crazy complex on how the homepage looks just yet though, what do you think about starting off with a simple design and then iterating on that in the future?

**Comment by JoltCode** [comment]
Yup sounds good haha, I'll do this, but after I've finished the accessibility issue and then I'll make some colours up while doing this (then I'll add a splash of our colours to the homepage)

**Comment by JoltCode** [comment]
I can do this 👍
