### ISSUE TITLE
[Web] [/contributors]: Contributors page to highlight OSS contributors

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#175]
### aspect

Other

### Suggestion?

I want a page to highlight the work of open source contributors so that recruiters can find them from the work that they have done

### Possible Solutions

![image](https://user-images.githubusercontent.com/39114868/219239073-f65dedc0-8123-4383-ba74-8d53f3566cf0.png)

**Comment by RhysSullivan** [comment]
References:

https://nextjs.org/conf/speakers
https://vercel.com/design
https://basement.studio/about

**Comment by JonahEpstein** [comment]
I can work on this
