### ISSUE TITLE
[Docs]: Add information about how the CLA works and licensing of code works to CONTRIBUTING.md

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#179]
### aspect

Contributing

### Suggestion?

It's important for everyone contributing to Answer Overflow to understand the CLA & license of the project so having a short description of that would be helpful

**Comment by JoltCode** [comment]
The link to the cla is https://cla-assistant.io/AnswerOverflow/AnswerOverflow
