### ISSUE TITLE
Search Result Page (/search)

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#18]
### What is this for?

website

### Feature

As a user, I want to be able to search and evaluate results from all communities on Answer Overflow to find the answers I'm looking for.

### Ideal solution or implementation

A search bar that takes you to a results page. The results page needs to have information such as:

- # Replies
- # Views
- Is Solved?
- Community

### Other context

View the existing search as a reference:

https://www.answeroverflow.com/search?q=How+do+I+turn+on+these+new+settings+for+my+help+channels%3F

**Comment by JoltCode** [comment]
I'll be doing this after the homepage issue is closed

**Comment by JoltCode** [comment]
Now under construction

**Comment by JoltCode** [comment]
![image](https://user-images.githubusercontent.com/46378904/220100125-14875566-f88b-4d14-a7f5-75842919bb9a.png)
First initial prototype of the ui

**Comment by JoltCode** [comment]
![Image](https://user-images.githubusercontent.com/46378904/220166839-bf624fdc-4818-4113-b3e3-f1b7a97d45cb.png)

**Comment by JoltCode** [comment]
And without answer (this does need tweaking however, need to adjust button sizes as it's looking a little weird

![Image](https://user-images.githubusercontent.com/46378904/220166997-b1de537c-c254-44a8-9e52-6aff9c01d7c1.png)

**Comment by RhysSullivan** [comment]
@JoltCode Can you post a figma url for us to comment on? Loving these early designs

**Comment by JoltCode** [comment]
> @JoltCode Can you post a figma url for us to comment on? Loving these early designs

Same one as the homepage, it's also on the guidelines PR 👍

Tysm!!

**Comment by JoltCode** [comment]
![image](https://user-images.githubusercontent.com/46378904/222802750-7e401f83-db68-4aa5-ae69-4c0af13b7a17.png)
Message result component is coming along 👍

**Comment by JoltCode** [comment]
Pretty much done, just need some final suggestions from @RhysSullivan regarding how we are going to "mock" this in storybook

**Comment by RhysSullivan** [comment]
@JoltCode Did you figure this one out from us talking?

**Comment by JoltCode** [comment]
Yup thanks! 👍
