### ISSUE TITLE
Create a milestone for the creation of input components

### ISSUE THREAD

**Issue by JoltCode** [AnswerOverflow/AnswerOverflow#195]
### Idea

We should use this issue for discussion of required input components, they should all be designed and styled so they can harmoniously work together and look awesome!

### Possible Solutions

Create a milestone on GitHub for the creation of input components

List required components
Create individual issues for each component to ensure we do not have issues and PRs which are too large.

### Extra Information

This will require us to decide upon an accent, slate, light slate and border colours, among other things.

**Comment by JoltCode** [comment]
@RhysSullivan

**Comment by JoltCode** [comment]
We need to do this and merge before we do the inputs on #76 and #18

**Comment by RhysSullivan** [comment]
Closed with https://github.com/AnswerOverflow/AnswerOverflow/milestone/4
