### ISSUE TITLE
Continuous Deployment 

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#20]
Setup a CD pipeline to deploy a staging version of the website and Discord bot based off the latest version of the main branch to ensure changes work in production

**Comment by JoltCode** [comment]
@RhysSullivan I believe the staging is (at least partially) done for the website, just the discord bot needs to be done as well...

**Comment by RhysSullivan** [comment]
Yep, I'll get that setup in the next few days - Haven't done it yet since I didn't want to pay to host the staging and prod bots until close to deployment @JoltCode

**Comment by JoltCode** [comment]
Sounds good!

**Comment by RhysSullivan** [comment]
Closing to split out into multiple issues
