### ISSUE TITLE
[Art]: Update Art Assets

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#200]
Update the art assets to look actually good

- [ ] Banner 
![image](https://user-images.githubusercontent.com/39114868/221034431-4608fc5d-cae7-4db1-bcf9-97b66918229b.png)
![image](https://user-images.githubusercontent.com/39114868/221034448-06428fb5-e67f-4c8b-acc9-a006580624eb.png)
![image](https://user-images.githubusercontent.com/39114868/221034554-ee8d95c8-8b0c-46d9-956f-0eae2f0361f3.png)

- [ ] Icon
![image](https://user-images.githubusercontent.com/39114868/221033630-1a59c173-1b74-4fe5-a970-ee6520969c64.png)

- [ ] Mascot 

- Something playful
- Maybe building off the @ symbol

- [ ] Brand color scheme

**Comment by Ness2025** [comment]
I can do this :)

**Comment by JoltCode** [comment]
Just related to this- we're currently redoing our colours (so perhaps that's something that we could look at Nene)? I've got a few colours that I came up with quickly, but I'd appreciate if we could look at it in a little more depth together 😄 :)

We also have new fonts in the design guidelines- these are pretty solid so I THINK we'll be sticking with them!
