### ISSUE TITLE
[Dev Env]: Add component update/change to issue template

### ISSUE THREAD

**Issue by JoltCode** [AnswerOverflow/AnswerOverflow#206]
### aspect

GitHub

### Suggestion?

Update the component issue template so it includes updating existing components, or create another template just for updates to existing components.

I would rather updating the old issue template, to avoid creating a large amount of templates.

### Possible Solutions

Create/update issue templates

### Extra Information

N/A

**Comment by JoltCode** [comment]
@RhysSullivan would you prefer another issue template or should we modify the existing one?

**Comment by RhysSullivan** [comment]
@JoltCode Let's modify the existing one
