### ISSUE TITLE
[Docs]: README subtitle wording

### ISSUE THREAD

**Issue by JoltCode** [AnswerOverflow/AnswerOverflow#210]
### aspect

README

### Suggestion?

Can we change:
> [Google Index Your Discord Help Channels](https://github.com/AnswerOverflow/AnswerOverflow#google-index-your-discord-help-channels)

To:
> Index your discord help channels to google

Currently, it doesnt sound great.

### Possible Solutions

Update readme with new wording

**Comment by JoltCode** [comment]
If that's okay @RhysSullivan I'll update 👍

**Comment by RhysSullivan** [comment]
Sure go for it @JoltCode
