### ISSUE TITLE
[Dev Env]: Add new input colors as global vars to tailwind config

### ISSUE THREAD

**Issue by JoltCode** [AnswerOverflow/AnswerOverflow#265]
### aspect

Design, Other

### Suggestion?

We should add the new input colors from the figma file as global vars to the tailwind config

**Comment by JoltCode** [comment]
Not sure if this is still applicable - @RhysSullivan should this be closed for now until we decide on future ui design changes that we've discussed in the AO discord?

**Comment by RhysSullivan** [comment]
closed for now
