### ISSUE TITLE
fix(bot): improve permissions error handling

### ISSUE THREAD

**Issue by JoltCode** [AnswerOverflow/AnswerOverflow#316]
### What is this bug report for?

discord bot

### Issue description

If the bot is missing permissions (for example to send embeds), it should notify the user rather than giving an error which isn't descriptive and appears somewhat unhandled  

### Code sample

```typescript
N/A
```

### Operating system

N/A

### Priority this issue should have

Medium (should be fixed soon)

**Comment by RhysSullivan** [comment]
track:https://www.notion.so/answeroverflow/Add-preconditions-and-permissions-to-DiscordJS-React-7ada6452cb4e4ea883eb0b10d6eaffdf?pvs=4
