### ISSUE TITLE
[Component]:  Allow indexing of top-level text channel.

### ISSUE THREAD

**Issue by zeel01** [AnswerOverflow/AnswerOverflow#317]
### Purpose?

The ability to allow the indexing of legacy text channels in order to make conversations that predate the threads of forums feature available and indexable.

### Concepts

This functionality could require additional steps to enable, with a disclaimer explaining why the results may not be optimal.

### Description

While it's understandable that the results of this sort of index might be poor, a poor index is still better than nothing. Additionally, the simple ability to access Discord messages from outside of Discord is valuable, even if the SEO isn't great.

But more importantly, in some cases there are legitimate "threads" that are in the form of text channels. On my server, before threads existed, we used a moderator bot's "ticket" system to create ad-hoc channels for specific purposes. These channels are essentially threads, and most have a definitive topic and narrow subject matter just like a thread would.

**Comment by RhysSullivan** [comment]
tracking: https://answeroverflow.notion.site/Put-normal-text-channels-in-sitemap-d06c2ac0cdb649ed83eebbb948e96699?pvs=4
