### ISSUE TITLE
(bot) /quick-start command

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#328]
/quick-setup command instead that runs through all the settings for you to get the best setup - that might provide a better initial UX

**Comment by RhysSullivan** [comment]
Goals:
- Simple command that someone runs to configure all the 
settings of a channel at the same time
- Reduce complexity of onboarding to answer overflow
by making it a one decision at a time process

Flow:
Use /quick-start in a channel

User has a menu created for them, walks them through each
setting in the format:

[Title]

[SHORT description]

[Enable] [Skip]

**Comment by RhysSullivan** [comment]
![image](https://user-images.githubusercontent.com/39114868/232179419-6d9b26a9-cd50-42b4-8a88-7bd520ea889f.png)

**Comment by RhysSullivan** [comment]
A lot of this work is done in the /channel-settings menu already, we may want to call this /quick-configure instead

Another thing is whether to include server settings in this command, imo, this command is for first time users to answer overflow who just want to run through the settings they can enable for their channel

**Comment by uerk-io** [comment]
Commenting so I'm tracked, this is Crayverted from Discord

**Comment by RhysSullivan** [comment]
tracking in: https://www.notion.so/answeroverflow/quick-start-command-ca5caef860904bd4aceaac8c3b17b3d3?pvs=4
