### ISSUE TITLE
feat(ui): auto generate community banner gradient

### ISSUE THREAD

**Issue by JoltCode** [AnswerOverflow/AnswerOverflow#333]
### Idea

On the community page, the gradient of the banner at the top of the page should be auto generated from the logo colors of the server

**Comment by JoltCode** [comment]
https://github.com/Vibrant-Colors/node-vibrant

**Comment by RhysSullivan** [comment]
tracking: https://www.notion.so/answeroverflow/Auto-generate-the-community-banner-gradient-5b6dbc77ded647b586b4ee0c6ff3daf5?pvs=4
