### ISSUE TITLE
bug(ui/home): arrow is not in middle of google section

### ISSUE THREAD

**Issue by JoltCode** [AnswerOverflow/AnswerOverflow#338]
### What is this bug report for?

ui

### Issue description

In the hero area, the arrow does not point to the middle of anything

### Code sample

```typescript
N/A
```

### Operating system

N/A

### Priority this issue should have

Low (slightly annoying)

### Extra

![image](https://user-images.githubusercontent.com/46378904/231268631-d3fea081-7fa4-4687-a43b-ca6efc32101f.png)

**Comment by RhysSullivan** [comment]
closing since we're gonna do a new hero section eventually
