### ISSUE TITLE
bug(ui/themes): Visible flash between themes on page load

### ISSUE THREAD

**Issue by JoltCode** [AnswerOverflow/AnswerOverflow#339]
### What is this bug report for?

website, ui

### Issue description

As the website loads, there is a visible flash between themes (light/dark - vice versa)

### Operating system

N/A

### Priority this issue should have

Medium (should be fixed soon)

### Extra

Visible in Google lighthouse loading slideshow

**Comment by RhysSullivan** [comment]
tracking: https://www.notion.so/answeroverflow/Visible-flash-between-themes-on-page-load-b96ed99060f344adb0ba31e0d9939dcc?pvs=4
