### ISSUE TITLE
[Docs]: add intents, permissions, and scopes to contributing docs

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#345]
### aspect

Contributing

### Suggestion?

title

**Comment by RhysSullivan** [comment]
and callback url http://localhost:3000/api/auth/callback/discord

**Comment by uerk-io** [comment]
![image](https://user-images.githubusercontent.com/38047633/232204748-c837298f-9cf9-47e6-b15f-fd5f747c7866.png)

This may be a good image to add for reference, so devs can quickly compare if they have the right permissions and generate a link
