### ISSUE TITLE
Consent popup not being honored?

### ISSUE THREAD

**Issue by andybak** [AnswerOverflow/AnswerOverflow#436]
Just added AnswerOverflow to our server and saw posts appearing from users who aren't active. Checked one user and they say they definitely hadn't clicked the "agree to be indexed" button.

**Comment by RhysSullivan** [comment]
Hey! It should be being honored, if not that's a bug - could you add me on Discord (username is rhyssul) and I'll investigate?

**Comment by RhysSullivan** [comment]
Resolved - consent is working correctly however Answer Overflow needs to do a better job about being clearer about how it works, action items are as follows:


forum post guidelines (fpg) consent not being avaliable to regular text channels needs to be clearer why it's missing 

fpg consent is possibly confusing to legacy users, maybe having a way for them to see how they consented wouldhelp

bug on website not showing the blurred messages

when you're signed in and viewing private messages, that needs to be clearer

@mentions need to not show the username of the user theyre mentioning if they arent consenting
