### ISSUE TITLE
Filter unsolved questions

### ISSUE THREAD

**Issue by saade** [AnswerOverflow/AnswerOverflow#475]
Since Discord doesn't support filtering out tags (like Github's `-label: Solved`), maybe add support for adding an `Unsolved` tag, and after the question is marked as solved, Answer Overflow removes the `Unsolved` tag

Thoughts?

**Comment by RhysSullivan** [comment]
I agree that'd be helpful - big picture I think it may be interesting to actually roll out own view of forum channels on the website

It'd let us have more customizability do some of the following things:
- TweetDeck style view with multiple tabs open
- GitHub style tag filtering w/ and/or
- Notifications on posts with specific tags, or by users with a certain role, etc

Obviously that's a lot bigger scope than just applying an unsolved tag to posts but it could be an interesting future project

**Comment by JoltCode** [comment]
Now tracked under the Answer Overflow notion - https://answeroverflow.notion.site/Ability-to-filter-message-results-unsolved-solved-b855db4c1df740ebb812304fb704b53b?pvs=4 - thanks for the suggestion! 😄
