### ISSUE TITLE
Incorrect URL path construction on dashboard

### ISSUE THREAD

**Issue by ProbablyRaging** [AnswerOverflow/AnswerOverflow#513]
Noting major, but figured I'd point it out.

When clicking the 'View Community' button on the server's dashboard page, it navigates to a 404 page because it is trying to construct the URL with the `app` subdomain that the dashboard pages use, but the community pages do not.

Actual:
`https://app.answeroverflow.com/c/820889004055855144`
Expected:
`https://answeroverflow.com/c/820889004055855144`

https://github.com/AnswerOverflow/AnswerOverflow/blob/63001f821ece93cbe642261a039be19a5fe406cd/packages/ui/src/utils/server.ts#L3C1-L5C3

**Comment by RhysSullivan** [comment]
Thanks for the report! We recently moved the dashboard over to app.answeroverflow.com and I forgot to update it from using a relative url - I've deployed a fix for this
