### ISSUE TITLE
Don't require environment variables at build time

### ISSUE THREAD

**Issue by Southpaw1496** [AnswerOverflow/AnswerOverflow#516]
Currently, AnswerOverflow checks for (and I assume bakes in) all the environment variables it needs at build time. While this works for the hosted instance, it means that anyone self-hosting AnswerOverflow will need to build their own image from scratch instead of being able to use pre-built images, which is a needless increase in complexity. Instead, the environment variables should be moved to only being required at runtime, instead of at build time.

## Drawbacks
In CI/CD pipelines where the image is being built anyway, such as the hosted instance, requiring the environment variables at build-time ensures that deployments with missing variables will never be deployed, because the build will fail first. To mitigate this, an environment variable such as `BUILD_REQUIRE_ENVARS` could be used to control whether environment variables are required at build-time, optionally restoring the classic functionality for deployments that benefit from it.

**Comment by RhysSullivan** [comment]
Added a new environment variable, add `SKIP_ENV_CHECK="true"` and it will skip validating your env vars

**Comment by Southpaw1496** [comment]
Shouldn't skipping ENV checks be the default, since that will be the vast majority of self-hosted deployments?

**Comment by RhysSullivan** [comment]
During the docker build for self hosting I can just set the default to be true there, for new contributors and my own deployment pipeline it's more dangerous to have it default true since then I'm missing the validation
