### ISSUE TITLE
Discord Statuses

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#52]
### What is this for?

bot

### Feature

As a developer of Answer Overflow, I want statuses in the bot profile to encourage users to visit the bot.

### Ideal solution or implementation

The ability to cycle through an array of statuses, possible ideas are:

100% Open Source!
Answering X questions
Indexing X channels
Helping X servers
X answered questions!

**Comment by Cole-Heigis** [comment]
I'll do that!
