### ISSUE TITLE
Search in a specific community

### ISSUE THREAD

**Issue by deadcoder0904** [AnswerOverflow/AnswerOverflow#543]
So I stumbled upon [this question](https://www.answeroverflow.com/m/1193958823417892884) through [google](https://www.google.com/search?q=dockerfile+drizzle) when i searched `dockerfile drizzle` & when I searched `docker` in the search input (not the top search icon), I got https://www.answeroverflow.com/search?q=docker

imo, it should search within drizzle & show drizzle results. that's better ux.

also, the input can have placeholder like `search in drizzle community`

the top icon can be used to search generally.

**Comment by deadcoder0904** [comment]
Oh and I searched in the input after clicking on [Drizzle Team](https://www.answeroverflow.com/c/1043890932593987624) & it still didn't search in Drizzle Team community even though the placeholder said `Search the Drizzle Team community`

**Comment by JoltCode** [comment]
> So I stumbled upon [this question](https://www.answeroverflow.com/m/1193958823417892884) through [google](https://www.google.com/search?q=dockerfile+drizzle) when i searched `dockerfile drizzle` & when I searched `docker` in the search input (not the top search icon), I got https://www.answeroverflow.com/search?q=docker
> 
> imo, it should search within drizzle & show drizzle results. that's better ux.
> 
> also, the input can have placeholder like `search in drizzle community`
> 
> the top icon can be used to search generally.

Thanks so much for the report - any feedback is really appreciated 😄!!

We are already aware of this issue, and it is tracked under [TAS-101 within the Answer Overflow Notion](https://answeroverflow.notion.site/811abd5d62454872955b00b858ee354c?v=6dcf84df66f7493b9513f6ce8b4e10bb&p=f919139ac29549e9962cf0b35626352d&pm=s), where you may view updates on it's status - me or @RhysSullivan will make sure to let you know when it's fixed as well!

Thanks again,
Jolt.

**Comment by RhysSullivan** [comment]
Should be fixed now, thanks @JoltCode for the quick PR!

**Comment by deadcoder0904** [comment]
thanks @JoltCode for the quick fix.

i am wondering why not address my 1st comment as well?

i think it'll be better ux. what do you think @RhysSullivan?

or maybe provide another search input parameter to search directly in a community when i stumble upon a specific community?

currently its 2-clicks. 1-click would be better.

**Comment by RhysSullivan** [comment]
Sorry I forgot to address those suggestions!

Agreed the search UX could be a lot better, I like the suggestion of having the default being searching the community you're on let's implement that @JoltCode
