### ISSUE TITLE
All links should hover on underline

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#604]

**Comment by MahendraBishnoi29** [comment]
will pick this one also @JoltCode

**Comment by RhysSullivan** [comment]
Thanks @MahendraBishnoi29 - if you need help with developing join the Discord and we can help out

**Comment by MahendraBishnoi29** [comment]
> Thanks @MahendraBishnoi29 - if you need help with developing join the Discord and we can help out

sure, thank you @RhysSullivan
