### ISSUE TITLE
Search page broken

### ISSUE THREAD

**Issue by mairas** [AnswerOverflow/AnswerOverflow#616]
Just noticed that the search page is broken. There's no input field but instead, an empty "Search Results" page is given right away.

**Comment by mairas** [comment]
![Uploading Screenshot 2024-05-23 at 10.49.31.png…]()

**Comment by RhysSullivan** [comment]
Fixed - thanks for letting me know!

**Comment by RhysSullivan** [comment]
We're going to improve the styling of the search page soon, just added the search bar back for small screensizes as a quick fix
