### ISSUE TITLE
Per-community sitemap

### ISSUE THREAD

**Issue by caesay** [AnswerOverflow/AnswerOverflow#633]
I found this PR https://github.com/AnswerOverflow/AnswerOverflow/pull/288 which seems to have added per-community and per-channel sitemaps, but the code no longer appears to be in main, and the url's from this pr (/c/{community}/{channel}/sitemap.xml) no longer seem to work.

I'd like to index my discord forum with a chatbot, and submit my community sitemap to my google search console. It would be great if these could be brought back?

**Comment by RhysSullivan** [comment]
Sure I’ll find some time this week to bring those back, seems helpful to have both

**Comment by RhysSullivan** [comment]
shipped
