### ISSUE TITLE
[BUG] Dashboard link in popper account menu leads to 404

### ISSUE THREAD

**Issue by SupItsTom** [AnswerOverflow/AnswerOverflow#638]
## Expected Behavior
Clicking the Dashboard button should link to `https://www.answeroverflow.com/c/<server_id>` or to onboarding.

## Current Behavior
Clicking the button sends you to a 404 error page `https://app.answeroverflow.com/dashboard`.
However, clicking the button on the `www.answeroverflow.com/c/<server_id>` page seems to work as intended.

## Possible Solution
Onboarding: Change `app.answeroverflow.com` to `www.answeroverflow.com` for it to go to onboarding instead.
Dashboard: Change `app.answeroverflow.com/dashboard` to `www.answeroverflow.com/c/<server_id>`.

## Steps to Reproduce
1. Login via Discord
2. Select a server from onboarding
3. Go to the top-right and click your avatar
4. Click the "Dashboard" button

## Context (Environment)
Clicking the Dashboard button on the analytics page should send you to the public dashboard of the server the button is clicked from.
This currently leads to a not found page and may be confusing for people to know where their server's indexed content is.

**Comment by SupItsTom** [comment]
Here is where this is handled in code:
[/packages/ui/src/navbar/user-dropdown.tsx#L26](https://github.com/AnswerOverflow/AnswerOverflow/blob/41bb983a044c13866694f8bb62375ccf05d7e52c/packages/ui/src/navbar/user-dropdown.tsx#L26)

**Comment by RhysSullivan** [comment]
fixed, dashboard will now redirect to first server with bot or onboarding

will adjust this in a bit to default to last selected server
