### ISSUE TITLE
Message Result Page (/m/[id])

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#73]
### What is this for?

website

### Feature

As a user, I want an easy to view message page that allows me to quickly find the solution to my problem

### Ideal solution or implementation

Porting the existing message page, demo https://www.answeroverflow.com/m/1034242084493856788

- [x] Have messages load from the id in the url
- [x] Display server invite for server & channel
- [x] Only display public messages
- [x] Highlight Root Message
- [x] Highlight Solution Message
- [x] Light mode support
- [x] Dark mode support
- [x] Search bar should contain query that lead to the page

![image](https://user-images.githubusercontent.com/39114868/212040575-33e50bb7-c7d5-4fb5-a342-d476875be4a3.png)

**Comment by RhysSullivan** [comment]
- Added basic pricing page
- Added Footer
- Updated Messages to include markdown support
- Added pricing bar
- Added non functioning search bar
- Added non functioning server invite
- Added message page
- Added /consent slash command

**Comment by JoltCode** [comment]
This should be updated at some point to match the new upcoming design changes (more on this once we have a greater understanding of how the new design system is going to look)

**Comment by JoltCode** [comment]
Up next, will need to make some requirements, a wireframe and design.
