### ISSUE TITLE
Community Page (c/[id])

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#76]
### What is this for?

website

### Feature

As a user, I want a way to search all the questions in a server and see what questions a community has

### Ideal solution or implementation

![image](https://user-images.githubusercontent.com/39114868/212041572-6c77a773-0dec-4735-9efb-6192cb8eef67.png)

**Comment by RhysSullivan** [comment]
@JoltCode can we keep them as two separate PRs to prevent having big PRs?

**Comment by JoltCode** [comment]
Yeah! Two seperate PR's just doing both atm

**Comment by JoltCode** [comment]
Up next
