### ISSUE TITLE
Contact Page (/contact)

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#79]
### What is this for?

bot

### Feature

As a person visiting the site I need a way to get in contact

### Ideal solution or implementation

Email, link to Discord, link to schedule time on my calendar

**Comment by RhysSullivan** [comment]
Yep, a page that links the email, discord server, github issues, and twitter for answer overflow would be good

**Comment by JoltCode** [comment]
Sounds good 👍
