### ISSUE TITLE
Terms of Servicer (/terms)

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#81]
### What is this for?

bot

### Feature

As a user, I need to know what the ToS is before signing up for Answer Overflow

### Ideal solution or implementation

A page with the ToS content

**Comment by JoltCode** [comment]
@RhysSullivan please can we have a rough ToS that we can use for this? Thanks 👍

**Comment by RhysSullivan** [comment]
@JoltCode Will DM you the draft
