### ISSUE TITLE
Finish Message Component

### ISSUE THREAD

**Issue by RhysSullivan** [AnswerOverflow/AnswerOverflow#84]
### What is this for?

website

### Feature

As a user, I want the message component to have parity with Discord messages so I can get all the information I need

### Ideal solution or implementation

- [x] Markdown Support
- [ ] #318
- [x] Monospace codeblock font
- [x] Opening images as modals
- [x] Code Blocks
- [x] Links to open in Discord & copy URL
- [x] Revisit Ignored Unescaped HTML

**Comment by RhysSullivan** [comment]
Markdown support & Code Blocks added with #99

**Comment by RhysSullivan** [comment]
XSS tests are a part of #100

**Comment by JoltCode** [comment]
Is this still relevant and needed?

**Comment by RhysSullivan** [comment]
Still needs opening images as modals and a test for escaping the HTML, I can write the test part

**Comment by JoltCode** [comment]
But what are we going to be using the message component for....?

**Comment by RhysSullivan** [comment]
This is for the message component that is rendered on the community page, search result page, and message result page - we might need to improve the wording on all of it to not have those confused with the component on the homepage

**Comment by JoltCode** [comment]
The new one?

**Comment by JoltCode** [comment]
Like the one in the new search result page?

**Comment by JoltCode** [comment]
> Opening images as modals
Done!

**Comment by JoltCode** [comment]
All done apart from replies - @RhysSullivan we need to discuss on how this will look ui/ux wise :+1:

**Comment by JoltCode** [comment]
I do also need to improve the look and functionality of the link and clipboard buttons in the message component!
